name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container:
            image: cuaesd/aesd-autotest:24-assignment5-buildroot
            options: --user root --privileged -v /home/kristian/.dl:/github/home/.dl
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2

          - name: Update container packages
            run: |
              apt-get update
              apt-get install -y util-linux
              flock --version
              which flock

          - name: Checkout submodules
            run: git submodule update --init --recursive
          
          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          - name: Fix permissions
            run: setfacl -R --remove-all . && setfacl -R --remove-default .
          
          - name: Run full test
            env:
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: ./full-test.sh

          - name: Cleanup
            if: always()
            run: ssh-add -D
